### ISSUE TITLE
Research which IDE we will use (Jdoodle or Monaco Editor)

### ISSUE THREAD

**Issue by GabrielPedroza** [upe-webdev-2/Web-Dev-II-Frontend#10]
Look at key points that we are searching for:

Overall Lightweight

(Ideal) Syntax highlighting

(Ideal) Ease of use

(Ideal) Good documentation so it would overall be straight-foward to implement

How would the users code be processed? (Would the website process the code or do we need to process it?)

(Ideal) Supports multiple languages

Any other crucial information that we need to know of

**Comment by sebastian-nunez** [comment]
# Why Monaco?

Since the beginning, I thought that embedding a version of VS Code into the browser was our best option:

1. Handles all syntax highlighting
2. Has IntelliSense and some autocomplete
3. clean UI

## Implementation

At first, I wasn't sure how easily we could embed Monaco into our site. After some research, I found an npm package called [monaco-editor/react](https://www.npmjs.com/package/@monaco-editor/react). For the most part, this package handles everything for us and makes Monaco extremely easy to embed. 

> The npm package reveals an "Editor" component which can be configured
```javascript
<Editor
  className="border-l-2"
  language={language}
  defaultValue={code}
  onChange={handleEditorChange}
  defaultLanguage={editorConfig.defaultLanguage}
  height={editorConfig.height}
  theme={editorConfig.theme}
  options={editorConfig.options}
/>
```

> Monaco Configuration
```javascript
const editorConfig = {
  theme: "vs",
  height: "80vh",
  defaultLanguage: "python",
  options: {
    minimap: {
      enabled: false
    },
    fontFamily: "JetBrains Mono",
    fontSize: 14,
    readOnly: false,
    smoothScrolling: true
  }
};
```

## Future Concerns: it is lightweight?

From the testing I've done so far, Monaco has been extremely responsive. Usually, 1-2 seconds of loading time. However, I'm not sure how 3D rendering might affect it. 
> If anything, I don't think we should have 3D while the player is coding.

**Comment by GabrielPedroza** [comment]
We most likely won't have any 3D in the same page as Monaco but this is a good consideration nonetheless. If there is any slowdown in respect to loading times, I'll figure out what to do to make sure everything is in compliance and if there's any drastic changes, I'll let the team know about it.
