### ISSUE TITLE
Once the IDE is decided, implement it in the coding page

### ISSUE THREAD

**Issue by GabrielPedroza** [upe-webdev-2/Web-Dev-II-Frontend#9]
Super rough prototype. Does not have to be perfect. Ideal to make it work but not mandatory. If too complicated, ask for help.
https://trello.com/b/5Hm2qPMu/codeclash-frontend

**Comment by sebastian-nunez** [comment]
# Check out the "Playground" Branch
> You have to follow the instructions on the README.
## Basic Home Screen
<img width="1440" alt="Screen Shot 2022-10-14 at 4 16 01 PM" src="https://user-images.githubusercontent.com/45319275/195934860-50e2f3c3-3517-4486-be93-438d2face11d.png">

## Playground Page
<img width="1440" alt="Screen Shot 2022-10-14 at 4 16 17 PM" src="https://user-images.githubusercontent.com/45319275/195934928-f52e5f06-d225-4fe2-be3a-f08dc17bc2b8.png">

**Comment by GabrielPedroza** [comment]
Holy shit!! This is an incredible start dude wow! I'm speechless on how fast this progressed

**Comment by styled-man** [comment]
This is looking astonishly good, solid work!! 👍 

I do have some concerns however:
1. We should remove the [`index.css`](https://github.com/upe-webdev-2/Web-Dev-II-Frontend/blob/playground/src/styles/index.css) file because tailwind already handles pretty much everything it is doing:
	- [vender prefixes](https://tailwindcss.com/docs/browser-support) for most modern broswers
	   > In general, Tailwind CSS v3.0 is designed for and tested on the latest stable versions of Chrome, Firefox, Edge, and Safari. It does not support any version of IE, including IE 11.   
	   > If you’re using the Tailwind CLI tool, vendor prefixes like this will be added automatically.

	-   It also has a set of [prefligth styles](https://tailwindcss.com/docs/preflight) that are automatically added to the project which remove some of the default margin, padding, borders... from elements like buttons anchor tags and more...
	    > Built on top of modern-normalize, Preflight is a set of base styles for Tailwind projects that are designed to smooth over cross-browser inconsistencies and make it easier for you to work within the constraints of your design system.

2. We should only write tailwind classes in the [`global.css`](https://github.com/upe-webdev-2/Web-Dev-II-Frontend/blob/playground/src/styles/global.css); If it is really unfeasable, then we should use vanilla css. That way we can take adventage of everything tailwind has to offer. 
```css
@layer base {
  body {
    @apply scroll-smooth font-jetbrains_mono;
  }
}
```
Don't forget to add the `jetbrains_mono` font in the [`tailwind.config.js`](https://github.com/upe-webdev-2/Web-Dev-II-Frontend/blob/master/tailwind.config.js).
```js
module.exports = {
  ...
  theme: {
    extend: {
      fontFamily: {
        jetbrains_mono: ["JetBrains Mono", "sans-serif"],
      },
    },
  },
  ...
};
```
